version: '3.8'

services:
  # Nginx làm Reverse Proxy cho Blue-Green Deployment
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    network_mode: host # Chạy cùng mạng host để dễ gọi các container app sau này

  # Jenkins để chạy CD Pipeline
  jenkins:
    image: jenkins/jenkins:lts
    user: root # Chạy quyền root để có thể gọi lệnh docker bên trong
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
      # Mount Docker socket để Jenkins có thể build/run Docker images
      - /var/run/docker.sock:/var/run/docker.sock 
      - /usr/bin/docker:/usr/bin/docker

volumes:
  jenkins_data: